service: code-redemption
frameworkVersion: ">=3.22.0"
variablesResolutionMode: 20210326

custom:
  scheduleEnabled:
    prod: true
    staging: false
    dev: false

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  timeout: 300
  memorySize: 256
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iam:PassRole"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:ReceiveMessage"
        - "sqs:SendMessage"
      Resource: 
        - { "Fn::GetAtt": ["CodeExpirationQueue", "Arn"] }
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:service}-hashes-${self:provider.stage}
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:service}-hashes-${self:provider.stage}/*
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:service}-domains-${self:provider.stage}
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:service}-domains-${self:provider.stage}/*
  environment:
    STAGE: ${self:provider.stage}
    CODE_TABLE_NAME: ${self:service}-hashes-${self:provider.stage}
    DOMAIN_TABLE_NAME: ${self:service}-domains-${self:provider.stage}
    CODE_EXPIRATION_QUEUE_URL:
      Ref: CodeExpirationQueue

functions:
  postCreateCode:
    handler: src/api/postCreateCode.handler
    timeout: 30
    events:
      - http:
          method: post
          path: /create
          cors: true
  postGenerateCode:
    handler: src/api/postGenerateCode.handler
    timeout: 30
    events:
      - http:
          method: post
          path: /generate
          cors: true
  postRedeemCode:
    handler: src/api/postRedeemCode.handler
    timeout: 30
    events:
      - http:
          method: post
          path: /redeem
          cors: true
  scheduleGetAllDomains:
    handler: src/scheduleGetAllDomains.fire
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: ${self:custom.scheduleEnabled.${self:provider.stage}}
  sqsExpireCodes:
    handler: src/sqsExpireCodes.receive
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CodeExpirationQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    # DynamoDB
    CodeDomains:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:service}-domains-${self:provider.stage}"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: code_domain
            AttributeType: S
        KeySchema:
          - AttributeName: code_domain
            KeyType: HASH
    CodeHashes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:service}-hashes-${self:provider.stage}"
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expire_timestamp
          Enabled: true
        AttributeDefinitions:
          - AttributeName: code_domain
            AttributeType: S
          - AttributeName: code_hash
            AttributeType: S
          - AttributeName: expire_timestamp
            AttributeType: "N"
        KeySchema:
          - AttributeName: code_domain
            KeyType: HASH
          - AttributeName: code_hash
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: expired_in_domain_GSI
            KeySchema:
              - AttributeName: code_domain
                KeyType: HASH
              - AttributeName: expire_timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    # SQS
    CodeExpirationDeadLetterQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: '${self:service}-deadLetter-${self:provider.stage}'
        MessageRetentionPeriod: 1209600 # Two weeks
        VisibilityTimeout: 60
    CodeExpirationQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: '${self:service}-${self:provider.stage}'
        MessageRetentionPeriod: 1209600 # Two weeks
        VisibilityTimeout: 900
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - CodeExpirationDeadLetterQueue
              - Arn
          maxReceiveCount: 2